// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace B7.Models;

public partial class Account
{
    public int Id { get; set; }

    public string AccountNumber { get; set; }

    public double Balance { get; set; }
}