// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace B7.Models;

public partial class Donation
{
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public string TypeOfDonation { get; set; }

    public double Amount { get; set; }

    public int? CheckNumber { get; set; }

    public string Notes { get; set; }

    public int DonerId { get; set; }
}